/// Para birimi kodları ve ülke anahtarları arasındaki eşleşme.
/// Ülke anahtarları çeviri servisinde 'country.{anahtar}' olarak kullanılır.
class ParaBirimleriData {
  static const Map<String, String> tumParaBirimleri = {
    'TRY': 'Turkey',
    'USD': 'USA',
    'EUR': 'EU',
    'GBP': 'UK',
    'SAR': 'SaudiArabia',
    'AED': 'UAE',
    'QAR': 'Qatar',
    'KWD': 'Kuwait',
    'BHD': 'Bahrain',
    'OMR': 'Oman',
    'JOD': 'Jordan',
    'JPY': 'Japan',
    'CNY': 'China',
    'RUB': 'Russia',
    'AZN': 'Azerbaijan',
    'CAD': 'Canada',
    'AUD': 'Australia',
    'CHF': 'Switzerland',
    'SEK': 'Sweden',
    'NOK': 'Norway',
    'DKK': 'Denmark',
    'EGP': 'Egypt',
    'IQD': 'Iraq',
    'IRR': 'Iran',
    'ILS': 'Israel',
    'GEL': 'Georgia',
    'UAH': 'Ukraine',
    'BGN': 'Bulgaria',
    'RON': 'Romania',
    'PLN': 'Poland',
    'HUF': 'Hungary',
    'CZK': 'CzechRepublic',
    'RSD': 'Serbia',
    'BAM': 'Bosnia',
    'MKD': 'Macedonia',
    'ALL': 'Albania',
    'KRW': 'SouthKorea',
    'INR': 'India',
    'BRL': 'Brazil',
    'MXN': 'Mexico',
    'ZAR': 'SouthAfrica',
  };
}
